##TODO - create simple dk_depend_ALL() to all all plugins.

dk_enable(HAVE_DKCef) ##FIXME: Find a way to remove this requirement

##dk_depend(doxygen-1.8.11)
dk_depend(DK)
dk_depend(DKDuktape)
dk_depend(DKArchive)
dk_depend(DKAssets)
dk_depend(DKAudio)
dk_depend(DKBuild)
##dk_depend(DKCef)
##dk_depend(DKCefChild)
##dk_depend(DKConsole)
dk_depend(DKCurl)
dk_depend(DKDebug)
dk_depend(DKDev)
dk_depend(DKDom)
dk_depend(DKEditor)
dk_depend(DKFile)
##dk_depend(DKGoogleAd)
dk_depend(DKGui)
dk_depend(DKHook)
dk_depend(DKLoading)
dk_depend(DKLogin)
dk_depend(DKMySql)
dk_depend(DKNotepad)
dk_depend(DKRml)
dk_depend(DKRmlIframe)
dk_depend(DKRmlVideo)
#dk_depend(DKScale)
dk_depend(DKSDLAudio)
dk_depend(DKSDLCef)
dk_depend(DKSDLRml)
##dk_depend(DKSDLVideo)
dk_depend(DKSDLWindow)
dk_depend(DKThread)
dk_depend(DKTooltip)
dk_depend(DKTray)
dk_depend(DKTriggers)
dk_depend(DKUpdate)
##dk_depend(DKVideo)
dk_depend(DKWidget)
dk_depend(DKWindow)
dk_depend(DKXml)