dk_enable(HAVE_DKCef) ##FIXME: Find a way to remove this requirement

dk_depend(DK)
dk_depend(DKDuktape)
dk_depend(DKArchive)
dk_depend(DKAssets)
dk_depend(DKDebug)
dk_depend(DKFile)
dk_depend(DKFtp)
##dk_depend(DKGoogleAd)
dk_depend(DKNotepad)
dk_depend(DKRml)
#dk_depend(DKScale)
dk_depend(DKSDLCef)
dk_depend(DKSDLRml)
dk_depend(DKSDLWindow)
dk_depend(DKTray)
dk_depend(DKThread)
dk_depend(DKWebview)
dk_depend(DKWidget)
dk_depend(DKWindow)