## http://tommy.chheng.com/post/123568080616/encode-opengl-to-video-with-opencv
dk_depend(DK)
dk_depend(DKArchive)
dk_depend(DKAssets)
dk_depend(DKDebug)
dk_depend(DKDom)
dk_depend(DKDuktape)
dk_depend(DKFile)
dk_depend(DKRml)
dk_depend(DKSDLRml)
dk_depend(DKSDLWindow)
dk_depend(DKScreenRecorder)
dk_depend(DKTray)
dk_depend(DKWindow)
