dk_enable(HAVE_DKCef) ##FIXME: Find a way to remove this requirement

dk_depend(DK)
dk_depend(DKDuktape)
dk_depend(DKCef)
dk_depend(DKDebug)
dk_depend(DKDom)
dk_depend(DKFile)
dk_depend(DKGui)
dk_depend(DKNotepad)
dk_depend(DKOcr)
dk_depend(DKPaint)
dk_depend(DKSDLRml)
dk_depend(DKTray)
dk_depend(DKUpdate)
dk_depend(DKWidget)
dk_depend(DKWindow)