dk_enable(HAVE_DKCef) ##FIXME: Find a way to remove this requirement

dk_depend(DK)
dk_depend(DKDuktape)
dk_depend(DKArchive)
dk_depend(DKAssets)
dk_depend(DKBrowser)
dk_depend(DKCef)
dk_depend(DKCefChild)
dk_depend(DKCurl)
dk_depend(DKDebug)
dk_depend(DKFile)
dk_depend(DKGoogleAd)
dk_depend(DKOSGCef)
dk_depend(DKOSGRocket)
dk_depend(DKOSGViewer)
dk_depend(DKOSGWindow)
dk_depend(DKRml)
dk_depend(DKThread)
dk_depend(DKUpdate)
dk_depend(DKWidget)
dk_depend(DKWindow)
dk_depend(DKXml)
